server:
  port: 9003

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://43.139.186.235:3306/interest?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
    enableStat: true